import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import AuthProvider from "@/components/authentication/session-provider";
import { Toaster } from "react-hot-toast";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import DashboardSidebar from "@/components/dashboard/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <AuthProvider>
            <SidebarProvider defaultOpen={false}>
              <DashboardSidebar />
              <SidebarInset>
                <header className="bg-sidebar text-sidebar-foreground border-b border-sidebar-border -ml-10 py-3">
                  <SidebarTrigger className="ml-16" />
                </header>
                <main className="w-full my-16 md:my-24">{children}</main>
              </SidebarInset>
            </SidebarProvider>
          </AuthProvider>
          <Toaster
            position="bottom-center"
            reverseOrder={false}
            toastOptions={{
              className: "bg-background text-foreground",
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
